// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from "@prisma/orm-postgres/adapter/operation-types";
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from "@prisma/orm-postgres/target/codec-types";

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from "@prisma/orm-postgres/family-contract/types";
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from "@prisma/orm-postgres/contract/types";

export type StorageHash =
  StorageHashBase<"5d7d8422985ee4655594cedb74b6478bdfdfbfd655b6e0489a302a48b35ceb7b">;
export type ExecutionHash =
  ExecutionHashBase<"a92a75c8cccb6ffdd9df420653331f96ba144b383203d67f0701f840426d416e">;
export type ProfileHash =
  ProfileHashBase<"3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2">;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly "pg/float@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/float4@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/float8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/time-string@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly "pg/int@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: {
      readonly output: "pg/int8number@1";
      readonly nullable: false;
    };
    readonly anyInput: {
      readonly output: "pg/int8number@1";
      readonly nullable: false;
    };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: {
      readonly output: "pg/int8@1";
      readonly nullable: false;
    };
    readonly anyInput: {
      readonly output: "pg/int8@1";
      readonly nullable: false;
    };
  };
  readonly max: {
    readonly byCodec: {
      readonly "pg/char@1": {
        readonly output: "pg/char@1";
        readonly nullable: true;
      };
      readonly "pg/date-string@1": {
        readonly output: "pg/date-string@1";
        readonly nullable: true;
      };
      readonly "pg/date-temporal@1": {
        readonly output: "pg/date-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/enum@1": {
        readonly output: "pg/enum@1";
        readonly nullable: true;
      };
      readonly "pg/float@1": {
        readonly output: "pg/float@1";
        readonly nullable: true;
      };
      readonly "pg/float4@1": {
        readonly output: "pg/float4@1";
        readonly nullable: true;
      };
      readonly "pg/float8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/inet@1": {
        readonly output: "pg/inet@1";
        readonly nullable: true;
      };
      readonly "pg/int@1": {
        readonly output: "pg/int@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/int2@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/int4@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/text-array@1": {
        readonly output: "pg/text-array@1";
        readonly nullable: true;
      };
      readonly "pg/text@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
      readonly "pg/time-string@1": {
        readonly output: "pg/time-string@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/time-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-string@1": {
        readonly output: "pg/timestamp-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-temporal@1": {
        readonly output: "pg/timestamp-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-string@1": {
        readonly output: "pg/timestamptz-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-temporal@1": {
        readonly output: "pg/timestamptz-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timetz@1": {
        readonly output: "pg/timetz@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/varchar@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
      readonly "sql/char@1": {
        readonly output: "sql/char@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": {
        readonly output: "sql/float@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "sql/int@1";
        readonly nullable: true;
      };
      readonly "sql/text@1": {
        readonly output: "sql/text@1";
        readonly nullable: true;
      };
      readonly "sql/varchar@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly "pg/char@1": {
        readonly output: "pg/char@1";
        readonly nullable: true;
      };
      readonly "pg/date-string@1": {
        readonly output: "pg/date-string@1";
        readonly nullable: true;
      };
      readonly "pg/date-temporal@1": {
        readonly output: "pg/date-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/enum@1": {
        readonly output: "pg/enum@1";
        readonly nullable: true;
      };
      readonly "pg/float@1": {
        readonly output: "pg/float@1";
        readonly nullable: true;
      };
      readonly "pg/float4@1": {
        readonly output: "pg/float4@1";
        readonly nullable: true;
      };
      readonly "pg/float8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/inet@1": {
        readonly output: "pg/inet@1";
        readonly nullable: true;
      };
      readonly "pg/int@1": {
        readonly output: "pg/int@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/int2@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/int4@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/text-array@1": {
        readonly output: "pg/text-array@1";
        readonly nullable: true;
      };
      readonly "pg/text@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
      readonly "pg/time-string@1": {
        readonly output: "pg/time-string@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/time-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-string@1": {
        readonly output: "pg/timestamp-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-temporal@1": {
        readonly output: "pg/timestamp-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-string@1": {
        readonly output: "pg/timestamptz-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-temporal@1": {
        readonly output: "pg/timestamptz-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timetz@1": {
        readonly output: "pg/timetz@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/varchar@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
      readonly "sql/char@1": {
        readonly output: "sql/char@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": {
        readonly output: "sql/float@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "sql/int@1";
        readonly nullable: true;
      };
      readonly "sql/text@1": {
        readonly output: "sql/text@1";
        readonly nullable: true;
      };
      readonly "sql/varchar@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly "pg/float@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/float4@1": {
        readonly output: "pg/float4@1";
        readonly nullable: true;
      };
      readonly "pg/float8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/time-string@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly "pg/int@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
    };
  };
};
type DefaultLiteralValue<
  CodecId extends string,
  Encoded,
> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]["json"]
    ? Encoded
    : CodecTypes[CodecId]["json"]
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly JobAuditLog: {
      readonly id: CodecTypes["pg/uuid@1"]["output"];
      readonly taskId: CodecTypes["pg/uuid@1"]["output"];
      readonly attemptNumber: CodecTypes["pg/int4@1"]["output"];
      readonly executionTime: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    };
    readonly RefreshToken: {
      readonly id: CodecTypes["pg/uuid@1"]["output"];
      readonly tokenHash: CodecTypes["pg/text@1"]["output"];
      readonly userId: CodecTypes["pg/uuid@1"]["output"];
      readonly revokedAt:
        CodecTypes["pg/timestamptz-temporal@1"]["output"] | null;
      readonly expiresAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    };
    readonly Task: {
      readonly id: CodecTypes["pg/uuid@1"]["output"];
      readonly userId: CodecTypes["pg/uuid@1"]["output"];
      readonly status: "PENDING" | "RUNNING" | "COMPLETED" | "FAILED";
      readonly payload: CodecTypes["pg/jsonb@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    };
    readonly User: {
      readonly id: CodecTypes["pg/uuid@1"]["output"];
      readonly email: CodecTypes["pg/text@1"]["output"];
      readonly passwordHash: CodecTypes["pg/text@1"]["output"];
      readonly role: "ADMIN" | "MEMBER";
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly JobAuditLog: {
      readonly id: CodecTypes["pg/uuid@1"]["input"];
      readonly taskId: CodecTypes["pg/uuid@1"]["input"];
      readonly attemptNumber: CodecTypes["pg/int4@1"]["input"];
      readonly executionTime: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
    };
    readonly RefreshToken: {
      readonly id: CodecTypes["pg/uuid@1"]["input"];
      readonly tokenHash: CodecTypes["pg/text@1"]["input"];
      readonly userId: CodecTypes["pg/uuid@1"]["input"];
      readonly revokedAt:
        CodecTypes["pg/timestamptz-temporal@1"]["input"] | null;
      readonly expiresAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
    };
    readonly Task: {
      readonly id: CodecTypes["pg/uuid@1"]["input"];
      readonly userId: CodecTypes["pg/uuid@1"]["input"];
      readonly status: "PENDING" | "RUNNING" | "COMPLETED" | "FAILED";
      readonly payload: CodecTypes["pg/jsonb@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
    };
    readonly User: {
      readonly id: CodecTypes["pg/uuid@1"]["input"];
      readonly email: CodecTypes["pg/text@1"]["input"];
      readonly passwordHash: CodecTypes["pg/text@1"]["input"];
      readonly role: "ADMIN" | "MEMBER";
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly jobAuditLog: {
      readonly attemptNumber: CodecTypes["pg/int4@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly executionTime: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly id: CodecTypes["pg/uuid@1"]["output"];
      readonly taskId: CodecTypes["pg/uuid@1"]["output"];
    };
    readonly refreshToken: {
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly expiresAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly id: CodecTypes["pg/uuid@1"]["output"];
      readonly revokedAt:
        CodecTypes["pg/timestamptz-temporal@1"]["output"] | null;
      readonly tokenHash: CodecTypes["pg/text@1"]["output"];
      readonly userId: CodecTypes["pg/uuid@1"]["output"];
    };
    readonly task: {
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly id: CodecTypes["pg/uuid@1"]["output"];
      readonly payload: CodecTypes["pg/jsonb@1"]["output"];
      readonly status: "PENDING" | "RUNNING" | "COMPLETED" | "FAILED";
      readonly updatedAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly userId: CodecTypes["pg/uuid@1"]["output"];
    };
    readonly user: {
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly email: CodecTypes["pg/text@1"]["output"];
      readonly id: CodecTypes["pg/uuid@1"]["output"];
      readonly passwordHash: CodecTypes["pg/text@1"]["output"];
      readonly role: "ADMIN" | "MEMBER";
      readonly updatedAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly jobAuditLog: {
      readonly attemptNumber: CodecTypes["pg/int4@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly executionTime: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly id: CodecTypes["pg/uuid@1"]["input"];
      readonly taskId: CodecTypes["pg/uuid@1"]["input"];
    };
    readonly refreshToken: {
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly expiresAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly id: CodecTypes["pg/uuid@1"]["input"];
      readonly revokedAt:
        CodecTypes["pg/timestamptz-temporal@1"]["input"] | null;
      readonly tokenHash: CodecTypes["pg/text@1"]["input"];
      readonly userId: CodecTypes["pg/uuid@1"]["input"];
    };
    readonly task: {
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly id: CodecTypes["pg/uuid@1"]["input"];
      readonly payload: CodecTypes["pg/jsonb@1"]["input"];
      readonly status: "PENDING" | "RUNNING" | "COMPLETED" | "FAILED";
      readonly updatedAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly userId: CodecTypes["pg/uuid@1"]["input"];
    };
    readonly user: {
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly email: CodecTypes["pg/text@1"]["input"];
      readonly id: CodecTypes["pg/uuid@1"]["input"];
      readonly passwordHash: CodecTypes["pg/text@1"]["input"];
      readonly role: "ADMIN" | "MEMBER";
      readonly updatedAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
    };
  };
};

export namespace Models {
  export type public_User = {
    id: CodecTypes["pg/uuid@1"]["output"];
    email: CodecTypes["pg/text@1"]["output"];
    passwordHash: CodecTypes["pg/text@1"]["output"];
    role: "ADMIN" | "MEMBER";
    createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    updatedAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    refreshTokens: public_RefreshToken[];
    tasks: public_Task[];
    readonly [RelationKeys]?: "refreshTokens" | "tasks";
  };
  export type public_RefreshToken = {
    id: CodecTypes["pg/uuid@1"]["output"];
    tokenHash: CodecTypes["pg/text@1"]["output"];
    userId: CodecTypes["pg/uuid@1"]["output"];
    revokedAt: CodecTypes["pg/timestamptz-temporal@1"]["output"] | null;
    expiresAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    user: public_User;
    readonly [RelationKeys]?: "user";
  };
  export type public_Task = {
    id: CodecTypes["pg/uuid@1"]["output"];
    userId: CodecTypes["pg/uuid@1"]["output"];
    status: "PENDING" | "RUNNING" | "COMPLETED" | "FAILED";
    payload: CodecTypes["pg/jsonb@1"]["output"];
    createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    updatedAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    auditLogs: public_JobAuditLog[];
    user: public_User;
    readonly [RelationKeys]?: "auditLogs" | "user";
  };
  export type public_JobAuditLog = {
    id: CodecTypes["pg/uuid@1"]["output"];
    taskId: CodecTypes["pg/uuid@1"]["output"];
    attemptNumber: CodecTypes["pg/int4@1"]["output"];
    executionTime: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    task: public_Task;
    readonly [RelationKeys]?: "task";
  };
}

export declare const models: {
  public: {
    User: Models.public_User;
    RefreshToken: Models.public_RefreshToken;
    Task: Models.public_Task;
    JobAuditLog: Models.public_JobAuditLog;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: "public";
        readonly kind: "postgres-schema";
        readonly entries: {
          readonly table: {
            readonly jobAuditLog: {
              columns: {
                readonly id: {
                  readonly nativeType: "uuid";
                  readonly codecId: "pg/uuid@1";
                  readonly nullable: false;
                };
                readonly taskId: {
                  readonly nativeType: "uuid";
                  readonly codecId: "pg/uuid@1";
                  readonly nullable: false;
                };
                readonly attemptNumber: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly executionTime: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-temporal@1";
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-temporal@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: "jobAuditLog_taskId_idx_4965c936";
                  readonly prefix: "jobAuditLog_taskId_idx";
                  readonly columns: readonly ["taskId"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "jobAuditLog";
                    readonly columns: readonly ["taskId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "task";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly refreshToken: {
              columns: {
                readonly id: {
                  readonly nativeType: "uuid";
                  readonly codecId: "pg/uuid@1";
                  readonly nullable: false;
                };
                readonly tokenHash: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: "uuid";
                  readonly codecId: "pg/uuid@1";
                  readonly nullable: false;
                };
                readonly revokedAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-temporal@1";
                  readonly nullable: true;
                };
                readonly expiresAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-temporal@1";
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-temporal@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["tokenHash"] }];
              indexes: readonly [
                {
                  readonly name: "refreshToken_userId_idx_a489d58a";
                  readonly prefix: "refreshToken_userId_idx";
                  readonly columns: readonly ["userId"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "refreshToken";
                    readonly columns: readonly ["userId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "user";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly task: {
              columns: {
                readonly id: {
                  readonly nativeType: "uuid";
                  readonly codecId: "pg/uuid@1";
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: "uuid";
                  readonly codecId: "pg/uuid@1";
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "literal";
                    readonly value: DefaultLiteralValue<"pg/text@1", "PENDING">;
                  };
                };
                readonly payload: {
                  readonly nativeType: "jsonb";
                  readonly codecId: "pg/jsonb@1";
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-temporal@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
                readonly updatedAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-temporal@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: "task_userId_idx_a489d58a";
                  readonly prefix: "task_userId_idx";
                  readonly columns: readonly ["userId"];
                  readonly unique: false;
                },
                {
                  readonly name: "task_status_idx_e98638ab";
                  readonly prefix: "task_status_idx";
                  readonly columns: readonly ["status"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "task";
                    readonly columns: readonly ["userId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "user";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly user: {
              columns: {
                readonly id: {
                  readonly nativeType: "uuid";
                  readonly codecId: "pg/uuid@1";
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly passwordHash: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly role: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "literal";
                    readonly value: DefaultLiteralValue<"pg/text@1", "MEMBER">;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-temporal@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
                readonly updatedAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-temporal@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["email"] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly TaskStatus: {
              readonly kind: "valueSet";
              readonly values: readonly [
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
              ];
            };
            readonly UserRole: {
              readonly kind: "valueSet";
              readonly values: readonly ["ADMIN", "MEMBER"];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  "roots" | "domain"
> & {
  readonly target: "postgres";
  readonly targetFamily: "sql";
  readonly roots: {
    readonly user: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "User";
    };
    readonly refreshToken: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "RefreshToken";
    };
    readonly task: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "Task";
    };
    readonly jobAuditLog: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "JobAuditLog";
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly JobAuditLog: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/uuid@1";
                };
              };
              readonly taskId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/uuid@1";
                };
              };
              readonly attemptNumber: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly executionTime: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-temporal@1";
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-temporal@1";
                };
              };
            };
            readonly relations: {
              readonly task: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Task";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["taskId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "jobAuditLog";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly taskId: { readonly column: "taskId" };
                readonly attemptNumber: { readonly column: "attemptNumber" };
                readonly executionTime: { readonly column: "executionTime" };
                readonly createdAt: { readonly column: "createdAt" };
              };
            };
          };
          readonly RefreshToken: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/uuid@1";
                };
              };
              readonly tokenHash: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/uuid@1";
                };
              };
              readonly revokedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-temporal@1";
                };
              };
              readonly expiresAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-temporal@1";
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-temporal@1";
                };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "User";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["userId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "refreshToken";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly tokenHash: { readonly column: "tokenHash" };
                readonly userId: { readonly column: "userId" };
                readonly revokedAt: { readonly column: "revokedAt" };
                readonly expiresAt: { readonly column: "expiresAt" };
                readonly createdAt: { readonly column: "createdAt" };
              };
            };
          };
          readonly Task: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/uuid@1";
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/uuid@1";
                };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly payload: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/jsonb@1";
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-temporal@1";
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-temporal@1";
                };
              };
            };
            readonly relations: {
              readonly auditLogs: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "JobAuditLog";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["taskId"];
                };
              };
              readonly user: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "User";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["userId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "task";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly userId: { readonly column: "userId" };
                readonly status: { readonly column: "status" };
                readonly payload: { readonly column: "payload" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly updatedAt: { readonly column: "updatedAt" };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/uuid@1";
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly passwordHash: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-temporal@1";
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-temporal@1";
                };
              };
            };
            readonly relations: {
              readonly refreshTokens: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "RefreshToken";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["userId"];
                };
              };
              readonly tasks: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Task";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["userId"];
                };
              };
            };
            readonly storage: {
              readonly table: "user";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly email: { readonly column: "email" };
                readonly passwordHash: { readonly column: "passwordHash" };
                readonly role: { readonly column: "role" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly updatedAt: { readonly column: "updatedAt" };
              };
            };
          };
        };
        readonly enum: {
          readonly UserRole: {
            readonly codecId: "pg/text@1";
            readonly members: readonly [
              { readonly name: "ADMIN"; readonly value: "ADMIN" },
              { readonly name: "MEMBER"; readonly value: "MEMBER" },
            ];
          };
          readonly TaskStatus: {
            readonly codecId: "pg/text@1";
            readonly members: readonly [
              { readonly name: "PENDING"; readonly value: "PENDING" },
              { readonly name: "RUNNING"; readonly value: "RUNNING" },
              { readonly name: "COMPLETED"; readonly value: "COMPLETED" },
              { readonly name: "FAILED"; readonly value: "FAILED" },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: "public";
            readonly table: "jobAuditLog";
            readonly column: "id";
          };
          readonly onCreate: {
            readonly kind: "generator";
            readonly id: "uuidv4";
          };
        },
        {
          readonly ref: {
            readonly namespace: "public";
            readonly table: "refreshToken";
            readonly column: "id";
          };
          readonly onCreate: {
            readonly kind: "generator";
            readonly id: "uuidv4";
          };
        },
        {
          readonly ref: {
            readonly namespace: "public";
            readonly table: "task";
            readonly column: "id";
          };
          readonly onCreate: {
            readonly kind: "generator";
            readonly id: "uuidv4";
          };
        },
        {
          readonly ref: {
            readonly namespace: "public";
            readonly table: "user";
            readonly column: "id";
          };
          readonly onCreate: {
            readonly kind: "generator";
            readonly id: "uuidv4";
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract["storage"]["namespaces"];
